# language is set to c to work around travis ci bug
# https://github.com/travis-ci/travis-ci/issues/2312
language: c
os:
  - osx
compiler:
  - clang
env:
  - TRAVIS_PYTHON_VERSION=3.4 TEST_SUITE_REGEX='^test_rstan'
  - TRAVIS_PYTHON_VERSION=3.4 TEST_SUITE_REGEX='^(?!test_rstan).*'
install: source continuous_integration/install.sh
script: bash continuous_integration/test_script.sh
